repos:
-   repo: local
    hooks:
    - id: pytest
      name: pytest
      language: system
      entry: bash -c 'pytest -v'
      stages: [commit]

-   repo: local
    hooks:
    - id: black
      name: black
      language: system
      entry: bash -c 'black app/ && git add app/'
      stages: [commit]

-   repo: local
    hooks:
    - id: isort
      name: isort
      language: system
      entry: bash -c 'isort app/ && git add app/'
      stages: [commit]

-   repo: local
    hooks:
    - id: addall
      name: addall
      language: system
      entry: bash -c 'git add app/'
      stages: [commit]